"""add sla fields to tickets

Revision ID: 196ea26bd174
Revises: 439a34ac266f
Create Date: 2026-09-03 09:19:25.087425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196ea26bd174'
down_revision: Union[str, Sequence[str], None] = '439a34ac266f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('sla_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_status')
    op.drop_column('tickets', 'resolution_time')
    op.drop_column('tickets', 'first_response_at')
    # ### end Alembic commands ###
