"""add sla management

Revision ID: f1f54ea0ab40
Revises: 3a4ce7f15a48
Create Date: 2026-09-03 08:52:31.599088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f54ea0ab40'
down_revision: Union[str, Sequence[str], None] = '3a4ce7f15a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_time_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_index(op.f('ix_sla_policies_id'), 'sla_policies', ['id'], unique=False)
    op.add_column('tickets', sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_deadline')
    op.drop_index(op.f('ix_sla_policies_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###
